### ISSUE TITLE
Different code block font size depending on the context

### ISSUE THREAD

**Issue by p0lycarp** [kinoute/typora-github-night-theme#5] opened 2021-03-17 09:51 UTC
This theme is great! The only thing that I noticed is that, for some reason, blocks of code have different font size depending on where they are.

For instance, in the screenshot below, the first code block (paragraph) is correct in size, while the second (bullet list) looks bigger:

<img width="665" alt="Screenshot 2021-03-17 at 10 51 32" src="https://user-images.githubusercontent.com/14147983/111448476-bde31580-870e-11eb-95bc-dbd6df1e02e8.png">

Is it possible to solve this problem?

**Comment by kinoute** [comment] 2021-03-17 09:54
Hello,

Could you send a me a markdown file that reproduces this issue?

Thanks!

**Comment by p0lycarp** [comment] 2021-03-17 09:57
Sure, here it is!
[Angr.md.zip](https://github.com/kinoute/typora-github-night-theme/files/6155360/Angr.md.zip)

**Comment by kinoute** [comment] 2021-03-17 10:00
It looks like it happens with code blocks are used in lists, am I right?

**Comment by p0lycarp** [comment] 2021-03-17 10:01
Exactly!

**Comment by kinoute** [comment] 2021-03-17 10:37
@p0lycarp I just pushed a fix to master, could you redownload the theme and tell me if it works now?

**Comment by p0lycarp** [comment] 2021-03-17 10:41
Amazing! Thank you so much 😁

**Comment by kinoute** [comment] 2021-03-17 10:47
Thanks for your report!

**Closed by kinoute** 2021-03-17 10:47 UTC
